// MPropertyFriendlyName = "Vsnd Radio Button"
// MPropertyDescription = "Plays vsnds based on membership in a numbered index."
// MHasKV3TransferPolymorphicClassname
class CVoiceContainerVsndRadioButton : public CVoiceContainerBase
{
	// MPropertyFriendlyName = "Namespace"
	CUtlString m_namespace;
	// MPropertyFriendlyName = "Vsnd 01"
	CVsndRadioButtonSlot m_slot1; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 02"
	CVsndRadioButtonSlot m_slot2; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 03"
	CVsndRadioButtonSlot m_slot3; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 04"
	CVsndRadioButtonSlot m_slot4; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 05"
	CVsndRadioButtonSlot m_slot5; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 06"
	CVsndRadioButtonSlot m_slot6; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 07"
	CVsndRadioButtonSlot m_slot7; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 08"
	CVsndRadioButtonSlot m_slot8; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 09"
	CVsndRadioButtonSlot m_slot9; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 10"
	CVsndRadioButtonSlot m_slot10; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 11"
	CVsndRadioButtonSlot m_slot11; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 12"
	CVsndRadioButtonSlot m_slot12; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 13"
	CVsndRadioButtonSlot m_slot13; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 14"
	CVsndRadioButtonSlot m_slot14; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 15"
	CVsndRadioButtonSlot m_slot15; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 16"
	CVsndRadioButtonSlot m_slot16; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_group": 1, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
};
