// MPropertyFriendlyName = "Vsnd Trigger"
// MPropertyDescription = "Plays vsnds based on trigger parameter changes."
// MHasKV3TransferPolymorphicClassname
class CVoiceContainerVsndTrigger : public CVoiceContainerBase
{
	// MPropertyFriendlyName = "Namespace"
	CUtlString m_namespace;
	// MPropertyFriendlyName = "Vsnd 01"
	CVsndTriggerSlot m_slot1; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 02"
	CVsndTriggerSlot m_slot2; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 03"
	CVsndTriggerSlot m_slot3; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 04"
	CVsndTriggerSlot m_slot4; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 05"
	CVsndTriggerSlot m_slot5; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 06"
	CVsndTriggerSlot m_slot6; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 07"
	CVsndTriggerSlot m_slot7; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 08"
	CVsndTriggerSlot m_slot8; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 09"
	CVsndTriggerSlot m_slot9; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 10"
	CVsndTriggerSlot m_slot10; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 11"
	CVsndTriggerSlot m_slot11; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 12"
	CVsndTriggerSlot m_slot12; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 13"
	CVsndTriggerSlot m_slot13; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 14"
	CVsndTriggerSlot m_slot14; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 15"
	CVsndTriggerSlot m_slot15; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
	// MPropertyFriendlyName = "Vsnd 16"
	CVsndTriggerSlot m_slot16; // = { "m_bEnableEndcap": false, "m_bEnableLoopcap": false, "m_bEnableVsnd": true, "m_endcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_fadeOut": 0, "m_loopcapVsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" }, "m_mode": "Trigger", "m_volume": 1, "m_vsnd": { "m_bUseReference": true, "m_namespace": "", "m_pSound": null, "m_sound": "" } }
};
